# -*- coding: utf-8 -*-
"""SQL 常见关键字与内置函数/类型。"""

import re

# 标准 SQL + 常用函数 + Hive/Spark 扩展
SQL_KEYWORDS = frozenset({
    # DML / DDL
    "SELECT", "FROM", "WHERE", "INSERT", "INTO", "UPDATE", "DELETE", "MERGE", "REPLACE",
    "CREATE", "ALTER", "DROP", "TRUNCATE", "RENAME", "COMMENT", "DESCRIBE", "DESC", "SHOW",
    "USE", "GRANT", "REVOKE", "COMMIT", "ROLLBACK", "SAVEPOINT", "BEGIN", "END", "TRANSACTION",
    "TABLE", "VIEW", "INDEX", "DATABASE", "SCHEMA", "SEQUENCE", "TRIGGER", "PROCEDURE", "FUNCTION",
    "EXTERNAL", "TEMPORARY", "TEMP", "IF", "EXISTS", "CASCADE", "RESTRICT", "PURGE",
    "OVERWRITE", "PARTITION", "PARTITIONED", "LOCATION", "STORED", "SERDE", "FORMAT",
    "CLUSTERED", "SORTED", "BUCKETS", "SKEWED", "ROW", "ROWS", "STORED", "INPUTFORMAT", "OUTPUTFORMAT",
    # JOIN
    "JOIN", "INNER", "LEFT", "RIGHT", "FULL", "OUTER", "CROSS", "NATURAL", "LATERAL", "ON", "USING",
    # 逻辑 / 条件
    "AND", "OR", "NOT", "IN", "IS", "NULL", "LIKE", "ILIKE", "RLIKE", "REGEXP", "SIMILAR", "ESCAPE",
    "BETWEEN", "EXISTS", "ANY", "ALL", "SOME", "DISTINCT", "UNIQUE", "CASE", "WHEN", "THEN", "ELSE",
    "TRUE", "FALSE", "UNKNOWN",
    # 分组 / 排序 / 窗口
    "GROUP", "BY", "HAVING", "ORDER", "ASC", "DESC", "NULLS", "FIRST", "LAST", "LIMIT", "OFFSET",
    "UNION", "INTERSECT", "EXCEPT", "MINUS", "WITH", "RECURSIVE", "AS", "OVER", "WINDOW",
    "PARTITION", "RANGE", "UNBOUNDED", "PRECEDING", "FOLLOWING", "CURRENT",
    # 约束
    "PRIMARY", "KEY", "FOREIGN", "REFERENCES", "CONSTRAINT", "DEFAULT", "CHECK", "ENABLE", "DISABLE",
    # 集合 / CTE
    "VALUES", "SET", "DISTRIBUTE", "SORT", "CLUSTER", "DISTRIBUTE", "MAP", "ARRAY", "STRUCT",
    # 类型
    "INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT", "FLOAT", "DOUBLE", "REAL", "DECIMAL", "NUMERIC",
    "BOOLEAN", "BOOL", "STRING", "VARCHAR", "CHAR", "TEXT", "BINARY", "VARBINARY", "BLOB", "CLOB",
    "DATE", "TIME", "TIMESTAMP", "DATETIME", "INTERVAL", "JSON", "UUID",
    # 聚合
    "COUNT", "SUM", "AVG", "MIN", "MAX", "STDDEV", "VARIANCE", "VAR_POP", "VAR_SAMP", "STDDEV_POP",
    "STDDEV_SAMP", "COLLECT_LIST", "COLLECT_SET", "GROUPING", "GROUPING_ID",
    # 字符串
    "CONCAT", "CONCAT_WS", "SUBSTRING", "SUBSTR", "TRIM", "LTRIM", "RTRIM", "UPPER", "LOWER",
    "LENGTH", "CHAR_LENGTH", "REPLACE", "TRANSLATE", "INSTR", "LOCATE", "POSITION", "LPAD", "RPAD",
    "SPLIT", "REGEXP_REPLACE", "REGEXP_EXTRACT", "REGEXP_SUBSTR", "FORMAT", "REVERSE", "REPEAT",
    # 数值
    "ABS", "CEIL", "CEILING", "FLOOR", "ROUND", "TRUNC", "MOD", "POWER", "SQRT", "EXP", "LN", "LOG",
    "LOG10", "LOG2", "SIGN", "RAND", "RANDOM", "GREATEST", "LEAST", "PI", "E",
    # 条件 / 空值
    "COALESCE", "NULLIF", "NVL", "NVL2", "IFNULL", "ISNULL", "IF", "DECODE", "IIF", "ZEROIFNULL",
    # 转换
    "CAST", "CONVERT", "TRY_CAST", "PARSE", "TO_CHAR", "TO_DATE", "TO_NUMBER", "TO_TIMESTAMP",
    "STR_TO_DATE", "DATE_FORMAT", "FROM_UNIXTIME", "UNIX_TIMESTAMP", "FROM_UTC_TIMESTAMP",
    "TO_UTC_TIMESTAMP",
    # 日期时间
    "NOW", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "SYSDATE", "GETDATE", "LOCALTIME",
    "LOCALTIMESTAMP", "EXTRACT", "DATE_ADD", "DATE_SUB", "DATEDIFF", "DATE_DIFF", "DATE_TRUNC",
    "ADD_MONTHS", "LAST_DAY", "NEXT_DAY", "MONTHS_BETWEEN", "YEAR", "MONTH", "DAY", "HOUR", "MINUTE",
    "SECOND", "WEEK", "QUARTER", "DAYOFWEEK", "DAYOFMONTH", "DAYOFYEAR",
    # 窗口函数
    "ROW_NUMBER", "RANK", "DENSE_RANK", "NTILE", "PERCENT_RANK", "CUME_DIST",
    "LAG", "LEAD", "FIRST_VALUE", "LAST_VALUE", "NTH_VALUE",
    # Hive / Spark
    "LATERAL", "VIEW", "EXPLODE", "POSEXPLODE", "INLINE", "STACK", "JSON_TUPLE", "GET_JSON_OBJECT",
    "NAMED_STRUCT", "TRANSFORM", "REDUCE", "AGGREGATE", "FILTER", "ZIP_WITH", "FLATTEN", "SEQUENCE",
    "EXPLODE_OUTER", "OUTER", "REFRESH", "MSCK", "REPAIR", "ANALYZE", "COMPUTE", "STATISTICS",
    "CACHE", "UNCACHE", "LOAD", "EXPORT", "IMPORT", "ADD", "JAR", "FILE", "ARCHIVE", "LIST", "DFS",
    "LOCAL", "DIRECTORY", "OPTION", "OPTIONS", "TBLPROPERTIES", "SERDEPROPERTIES", "TYPE", "MID",
    "DELIMITED", "FIELDS", "TERMINATED", "COLLECTION", "ITEMS", "KEYS", "LINES", "ESCAPED",
    "STORED", "AS", "ORC", "PARQUET", "AVRO", "JSONFILE", "TEXTFILE", "RCFILE", "SEQUENCEFILE",
    "INPUTFORMAT", "OUTPUTFORMAT", "BUCKET", "BUCKETS", "SKEWED", "SAMPLE", "PERCENT", "BYTE",
    "CAST", "STRING", "BOOLEAN",
})

_ORDERED_KEYWORDS = sorted(SQL_KEYWORDS, key=len, reverse=True)
KEYWORD_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(k) for k in _ORDERED_KEYWORDS) + r")\b",
    re.IGNORECASE,
)


def is_sql_keyword(name: str) -> bool:
    return name.upper() in SQL_KEYWORDS
