# -*- coding: utf-8 -*-
"""加解密算法目录与说明。"""

from typing import Any, Dict, List, Optional

AlgorithmMeta = Dict[str, Any]

ALGORITHMS: List[AlgorithmMeta] = [
    # 编码
    {
        "id": "base64",
        "name": "Base64",
        "category": "encoding",
        "category_zh": "编码",
        "actions": ["encode", "decode"],
        "intro": "Base64 将二进制数据编码为 ASCII 字符串，广泛用于 HTTP、JWT、邮件附件等场景。",
        "python_pkg": "标准库 base64",
        "js_pkg": "浏览器 btoa/atob 或 crypto-js",
        "fields": [],
        "output_format": "text",
    },
    {
        "id": "base64url",
        "name": "Base64 URL",
        "category": "encoding",
        "category_zh": "编码",
        "actions": ["encode", "decode"],
        "intro": "URL 安全 Base64，将 +/ 替换为 -_，省略填充 =，常用于 JWT。",
        "python_pkg": "标准库 base64.urlsafe_b64encode",
        "js_pkg": "crypto-js enc.Base64url",
        "fields": [],
        "output_format": "text",
    },
    {
        "id": "hex",
        "name": "Hex 十六进制",
        "category": "encoding",
        "category_zh": "编码",
        "actions": ["encode", "decode"],
        "intro": "将字节转为十六进制字符串，逆向分析中常用于查看密文。",
        "python_pkg": "bytes.hex() / bytes.fromhex()",
        "js_pkg": "Buffer.from(s,'hex')",
        "fields": [],
        "output_format": "text",
    },
    {
        "id": "url",
        "name": "URL 编码",
        "category": "encoding",
        "category_zh": "编码",
        "actions": ["encode", "decode"],
        "intro": "Percent-encoding，用于 URL 查询参数与表单提交。",
        "python_pkg": "urllib.parse.quote / unquote",
        "js_pkg": "encodeURIComponent / decodeURIComponent",
        "fields": [],
        "output_format": "text",
    },
    # 哈希
    {
        "id": "md5",
        "name": "MD5",
        "category": "hash",
        "category_zh": "哈希",
        "actions": ["hash"],
        "intro": "128 位摘要，已不推荐用于安全场景，但仍常见于 legacy sign。",
        "python_pkg": "hashlib.md5",
        "js_pkg": "crypto-js MD5",
        "fields": [],
        "output_format": "hex",
    },
    {
        "id": "sha1",
        "name": "SHA-1",
        "category": "hash",
        "category_zh": "哈希",
        "actions": ["hash"],
        "intro": "160 位摘要，Git、旧版 TLS 曾广泛使用。",
        "python_pkg": "hashlib.sha1",
        "js_pkg": "crypto-js SHA1",
        "fields": [],
        "output_format": "hex",
    },
    {
        "id": "sha256",
        "name": "SHA-256",
        "category": "hash",
        "category_zh": "哈希",
        "actions": ["hash"],
        "intro": "256 位摘要，比特币、TLS、JWT 等主流算法。",
        "python_pkg": "hashlib.sha256",
        "js_pkg": "crypto-js SHA256",
        "fields": [],
        "output_format": "hex",
    },
    {
        "id": "sha512",
        "name": "SHA-512",
        "category": "hash",
        "category_zh": "哈希",
        "actions": ["hash"],
        "intro": "512 位摘要，安全性高于 SHA-256，计算稍慢。",
        "python_pkg": "hashlib.sha512",
        "js_pkg": "crypto-js SHA512",
        "fields": [],
        "output_format": "hex",
    },
    {
        "id": "sm3",
        "name": "SM3 国密哈希",
        "category": "guomi",
        "category_zh": "国密",
        "actions": ["hash"],
        "intro": "国密 SM3 杂凑算法，256 位输出，对标 SHA-256。",
        "python_pkg": "gmssl.sm3",
        "js_pkg": "sm-crypto sm3",
        "fields": [],
        "output_format": "hex",
        "requires": ["gmssl"],
    },
    {
        "id": "hmac-md5",
        "name": "HMAC-MD5",
        "category": "hash",
        "category_zh": "哈希",
        "actions": ["hash"],
        "intro": "带密钥的 MD5 消息认证码，常见于 API 签名。",
        "python_pkg": "hmac + hashlib.md5",
        "js_pkg": "crypto-js HmacMD5",
        "fields": ["key"],
        "output_format": "hex",
    },
    {
        "id": "hmac-sha256",
        "name": "HMAC-SHA256",
        "category": "hash",
        "category_zh": "哈希",
        "actions": ["hash"],
        "intro": "带密钥的 SHA256，AWS Signature V4、JWT HS256 等使用。",
        "python_pkg": "hmac + hashlib.sha256",
        "js_pkg": "crypto-js HmacSHA256",
        "fields": ["key"],
        "output_format": "hex",
    },
    # 对称
    {
        "id": "aes-128-cbc",
        "name": "AES-128-CBC",
        "category": "symmetric",
        "category_zh": "对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "AES 128 位密钥 + CBC 模式 + PKCS7 填充，最常用的对称加密组合之一。",
        "python_pkg": "cryptography",
        "js_pkg": "crypto-js AES",
        "fields": ["key", "iv"],
        "key_len": 16,
        "iv_len": 16,
        "output_format": "base64",
    },
    {
        "id": "aes-256-cbc",
        "name": "AES-256-CBC",
        "category": "symmetric",
        "category_zh": "对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "AES 256 位密钥 + CBC，安全性更高，逆向中常见。",
        "python_pkg": "cryptography",
        "js_pkg": "crypto-js AES",
        "fields": ["key", "iv"],
        "key_len": 32,
        "iv_len": 16,
        "output_format": "base64",
    },
    {
        "id": "aes-256-ecb",
        "name": "AES-256-ECB",
        "category": "symmetric",
        "category_zh": "对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "ECB 模式无 IV，相同明文块产生相同密文，不推荐但仍常见。",
        "python_pkg": "cryptography",
        "js_pkg": "crypto-js AES (mode.ECB)",
        "fields": ["key"],
        "key_len": 32,
        "output_format": "base64",
    },
    {
        "id": "aes-256-gcm",
        "name": "AES-256-GCM",
        "category": "symmetric",
        "category_zh": "对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "AEAD 模式，同时提供加密与认证，输出含 16 字节 tag。",
        "python_pkg": "cryptography",
        "js_pkg": "Node.js crypto.createCipheriv('aes-256-gcm')",
        "fields": ["key", "iv", "aad"],
        "key_len": 32,
        "iv_len": 12,
        "output_format": "base64",
        "note": "解密时需传入 tag（加密结果末尾 16 字节）",
    },
    {
        "id": "des-cbc",
        "name": "DES-CBC",
        "category": "symmetric",
        "category_zh": "对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "56 位有效密钥，已不安全，老系统与逆向样本中仍可见。",
        "python_pkg": "cryptography (TripleDES/DES)",
        "js_pkg": "crypto-js TripleDES/DES",
        "fields": ["key", "iv"],
        "key_len": 8,
        "iv_len": 8,
        "output_format": "base64",
    },
    {
        "id": "3des-cbc",
        "name": "3DES-CBC",
        "category": "symmetric",
        "category_zh": "对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "三重 DES，密钥 24 字节，金融 legacy 系统常见。",
        "python_pkg": "cryptography TripleDES",
        "js_pkg": "crypto-js TripleDES",
        "fields": ["key", "iv"],
        "key_len": 24,
        "iv_len": 8,
        "output_format": "base64",
    },
    {
        "id": "sm4-ecb",
        "name": "SM4-ECB 国密",
        "category": "guomi",
        "category_zh": "国密",
        "actions": ["encrypt", "decrypt"],
        "intro": "国密 SM4 分组密码 ECB 模式，密钥 128 位。",
        "python_pkg": "gmssl.sm4",
        "js_pkg": "sm-crypto sm4",
        "fields": ["key"],
        "key_len": 16,
        "output_format": "hex",
        "requires": ["gmssl"],
    },
    {
        "id": "sm4-cbc",
        "name": "SM4-CBC 国密",
        "category": "symmetric",
        "category_zh": "对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "国密 SM4 CBC 模式，需 16 字节 IV。",
        "python_pkg": "gmssl.sm4",
        "js_pkg": "sm-crypto sm4",
        "fields": ["key", "iv"],
        "key_len": 16,
        "iv_len": 16,
        "output_format": "hex",
        "requires": ["gmssl"],
    },
    # 非对称
    {
        "id": "rsa-oaep",
        "name": "RSA-OAEP",
        "category": "asymmetric",
        "category_zh": "非对称加密",
        "actions": ["encrypt", "decrypt"],
        "intro": "RSA 最优非对称加密填充 OAEP(SHA256)，公钥加密私钥解密。",
        "python_pkg": "cryptography",
        "js_pkg": "Node.js crypto.publicEncrypt",
        "fields": ["public_key", "private_key"],
        "output_format": "base64",
        "note": "加密用公钥 PEM，解密用私钥 PEM，可点击生成密钥对",
    },
    {
        "id": "sm2",
        "name": "SM2 国密",
        "category": "guomi",
        "category_zh": "国密",
        "actions": ["encrypt", "decrypt"],
        "intro": "国密 SM2 椭圆曲线公钥加密，C1C3C2 模式。",
        "python_pkg": "gmssl.sm2",
        "js_pkg": "sm-crypto sm2",
        "fields": ["public_key", "private_key"],
        "output_format": "hex",
        "requires": ["gmssl"],
        "note": "公钥/私钥为 hex 字符串，可生成密钥对",
    },
]

CATEGORIES = [
    {"id": "encoding", "name": "编码", "icon": "🔤"},
    {"id": "hash", "name": "哈希/HMAC", "icon": "#"},
    {"id": "symmetric", "name": "对称加密", "icon": "🔒"},
    {"id": "asymmetric", "name": "非对称加密", "icon": "🔑"},
    {"id": "guomi", "name": "国密", "icon": "🇨🇳"},
]


def get_algorithm(algorithm_id: str) -> Optional[AlgorithmMeta]:
    for item in ALGORITHMS:
        if item["id"] == algorithm_id:
            return item
    return None


def list_catalog() -> dict:
    return {"categories": CATEGORIES, "algorithms": ALGORITHMS}
